title: Auditing race and gender inequality in data science related job market
description: Sahil Wadhwa, Nancy Jiang
github:
  zip_url: https://github.com/sawadhwa/sawadhwa.github.io
  another_url: https://www.google.com/

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
