theme: jekyll-theme-slate
title: Auditing race and gender inequality in data science related job market
description: Sahil Wadhwa, Nancy Jiang
             Halicioglu Data Science Institute, University of California, San Diego 

