title: Auditing race and gender inequality in data science related job market
description: Sahil Wadhwa, Nancy Jiang
url: https://sawadhwa.github.io/

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
